//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_DSWI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int COD_EMP { get; set; }
        public string NOM_EMP { get; set; }
        public string APE_EMP { get; set; }
        public int CEL_EMP { get; set; }
        public string CORREO_EMP { get; set; }
        public string DIRECCION_EMP { get; set; }
        public decimal SUELDO { get; set; }
        public string CONTRASEÑA { get; set; }
        public Nullable<int> ID_DIS { get; set; }
        public string FOTO_EMP { get; set; }
        public Nullable<System.DateTime> FEC_NAC_EMP { get; set; }
        public Nullable<int> ID_TIP { get; set; }
    
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual TIP_EMP TIP_EMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
