//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_DSWI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public int ID_PEDIDO { get; set; }
        public Nullable<int> ID_EMP { get; set; }
        public Nullable<System.DateTime> FEC_PEDIDO { get; set; }
        public Nullable<System.DateTime> FIN_PEDIDO { get; set; }
        public string ENV_PEDIDO { get; set; }
        public Nullable<int> CANT_PEDIDO { get; set; }
        public Nullable<int> ID_CLIE { get; set; }
        public string DET_PEDIDO { get; set; }
        public int ID_EMPLEADO { get; set; }
        public Nullable<int> ID_DIS { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual DETALLE_PED DETALLE_PED { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
