//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_DSWI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLE_PED = new HashSet<DETALLE_PED>();
        }
    
        public int ID_PROD { get; set; }
        public string NOM_PRO { get; set; }
        public int ID_TIP_PRO { get; set; }
        public int STOCK_PROD { get; set; }
        public decimal PRECIO { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_PROV { get; set; }
        public string FOTO_PROD { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_PED> DETALLE_PED { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
